JP-3096 :Jump keywords
spacetelescope/stdatamodels pull request #173
Opened 2023-06-15 19:49 UTC by mwregan2

Resolves [JP-3096](https://jira.stsci.edu/browse/JP-3096)

This PR adds two FITS header keywords that track the rate of regular cosmic rays and shower/snowballs.

**Checklist**
- [ ] added entry in `CHANGES.rst` (either in `Bug Fixes` or `Changes to API`)
- [ x] updated relevant tests
- [ x] updated relevant documentation
- [ ] updated relevant milestone(s)
- [ ] added relevant label(s)

2023-06-21 12:26 UTC, hbushouse reviewed
Needs a change log entry.

2023-06-21 12:26 UTC, hbushouse commented on src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
> +            title: Rate of Cosmic Rays per thousand pixels per second
```suggestion
            title: Cosmic Ray rate per thousand pixels per second
```
Original title string is too long to fit within FITS rec without being truncated.

2023-06-23 15:29 UTC, hbushouse requested changes
Still needs a change log entry so that we can merge. @mwregan2

2023-06-23 16:25 UTC, mwregan2 commented
I updated changes.rst in stdatamodels


From: Howard Bushouse ***@***.***>
Reply-To: spacetelescope/stdatamodels ***@***.***>
Date: Friday, June 23, 2023 at 11:29 AM
To: spacetelescope/stdatamodels ***@***.***>
Cc: Michael Regan ***@***.***>, Mention ***@***.***>
Subject: Re: [spacetelescope/stdatamodels] JP-3096: Add new JWST keywords to track CR's detected by the jump step (PR #173)


@hbushouse requested changes on this pull request.

Still needs a change log entry so that we can merge. @mwregan2<https://urldefense.com/v3/__https:/github.com/mwregan2__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!1kwcpJ5I1jTdww3sewjU_GL3rw85zH3MplXCjVb2GPmq1_945mR6gfQOKb9yLppru54FXlg_IJhFoo81sERZ_VY$>

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https:/github.com/spacetelescope/stdatamodels/pull/173*pullrequestreview-1495370376__;Iw!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!1kwcpJ5I1jTdww3sewjU_GL3rw85zH3MplXCjVb2GPmq1_945mR6gfQOKb9yLppru54FXlg_IJhFoo81gpyHljQ$>, or unsubscribe<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/AF6KJLQLPDDSKVR66WYMMS3XMWY7DANCNFSM6AAAAAAZIKFHKE__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!1kwcpJ5I1jTdww3sewjU_GL3rw85zH3MplXCjVb2GPmq1_945mR6gfQOKb9yLppru54FXlg_IJhFoo819lAnjJs$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-06-23 16:39 UTC, hbushouse commented on CHANGES.rst
> +  rays (Snowballs and Showers)
```suggestion
jwst.datamodels
---------------
- Added two new header keywords to the JWST exposure section: PRIMECRS and
  EXTNCRS, which are used to record the rate of primary cosmic rays and extended cosmic
  rays (Snowballs and Showers). [#173]
```

2023-06-23 17:25 UTC, hbushouse approved these changes

2023-06-23 17:25 UTC, merged